# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-25 22:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='description',
            field=models.CharField(default='coming soon...', max_length=500),
        ),
    ]
